--
-- Script was generated by Devart dbForge Studio 2020 for PostgreSQL, Version 2.3.230.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 20.09.2021 15:00:50
-- Server version: PostgreSQL 13.1
--


INSERT INTO work.public.peoples(name, patronymic, surname) VALUES
(E'Михайл', E'Саввич', E'Тукшов');
INSERT INTO work.public.peoples(name, patronymic, surname) VALUES
(E'Александр', E'Иванович', E'Покрышкин');
INSERT INTO work.public.peoples(name, patronymic, surname) VALUES
(E'Александр', E'Семенович', E'Горбунков');
INSERT INTO work.public.peoples(name, patronymic, surname) VALUES
(E'Дмитрий', E'Андреевич', E'Джанибеков');
INSERT INTO work.public.peoples(name, patronymic, surname) VALUES
(E'Андрей', E'Николаевич', E'Песков');
INSERT INTO work.public.peoples(name, patronymic, surname) VALUES
(E'Михаил', E'Андреевич', E'Авдеев');
INSERT INTO work.public.peoples(name, patronymic, surname) VALUES
(E'Валентина', E'Прокопьевна', E'Ушкарева');
INSERT INTO work.public.peoples(name, patronymic, surname) VALUES
(E'Владимир', E'Абрамович', E'Яковлев');
INSERT INTO work.public.peoples(name, patronymic, surname) VALUES
(E'Альберт', E'Александрович', E'Мазжерин');
INSERT INTO work.public.peoples(name, patronymic, surname) VALUES
(E'Анатолий', E'Григорьевич', E'Мухамедшин');
INSERT INTO work.public.peoples(name, patronymic, surname) VALUES
(E'Илья', E'Петрович', E'Герасимов');