--
-- Script was generated by Devart dbForge Studio 2020 for PostgreSQL, Version 2.3.230.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 20.09.2021 15:00:50
-- Server version: PostgreSQL 13.1
--


INSERT INTO work.public.peoples(id, name, patronymic, surname) VALUES
(1, E'Михайл', E'Саввич', E'Тукшов');
INSERT INTO work.public.peoples(id, name, patronymic, surname) VALUES
(3, E'Александр', E'Иванович', E'Покрышкин');
INSERT INTO work.public.peoples(id, name, patronymic, surname) VALUES
(4, E'Александр', E'Семенович', E'Горбунков');
INSERT INTO work.public.peoples(id, name, patronymic, surname) VALUES
(5, E'Дмитрий', E'Андреевич', E'Джанибеков');
INSERT INTO work.public.peoples(id, name, patronymic, surname) VALUES
(8, E'Андрей', E'Николаевич', E'Песков');
INSERT INTO work.public.peoples(id, name, patronymic, surname) VALUES
(15, E'Михаил', E'Андреевич', E'Авдеев');
INSERT INTO work.public.peoples(id, name, patronymic, surname) VALUES
(13, E'Валентина', E'Прокопьевна', E'Ушкарева');
INSERT INTO work.public.peoples(id, name, patronymic, surname) VALUES
(6, E'Владимир', E'Абрамович', E'Яковлев');
INSERT INTO work.public.peoples(id, name, patronymic, surname) VALUES
(10, E'Альберт', E'Александрович', E'Мазжерин');
INSERT INTO work.public.peoples(id, name, patronymic, surname) VALUES
(2, E'Анатолий', E'Григорьевич', E'Мухамедшин');
INSERT INTO work.public.peoples(id, name, patronymic, surname) VALUES
(19, E'Илья', E'Петрович', E'Герасимов');